### ISSUE TITLE
Don't work with windows  on powershell

### ISSUE THREAD

**Issue by albertorugnone** [bahmutov/all-nvm#6]
The module fails when I run it on windows because it can't find sh as command

> "sh" non è riconosciuto come comando interno o esterno,
>  un programma eseguibile o un file batch.

means "sh is not a command"

```

PS C:\> all npm i -g eslint
=====================================================================================================================================================================================
Running command on Node 7.9.0 [ 'npm', 'i', '-g', 'eslint' ]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
"sh" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
prog error
{ Error: spawn sh ENOENT
    at notFoundError (C:\Users\arugnone\AppData\Roaming\nvm\v6.10.2\node_modules\all-nvm\node_modules\cross-spawn-async\lib\enoent.js:8:11)
    at verifyENOENT (C:\Users\arugnone\AppData\Roaming\nvm\v6.10.2\node_modules\all-nvm\node_modules\cross-spawn-async\lib\enoent.js:43:16)
    at ChildProcess.cp.emit (C:\Users\arugnone\AppData\Roaming\nvm\v6.10.2\node_modules\all-nvm\node_modules\cross-spawn-async\lib\enoent.js:30:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12) errno: 'ENOENT', code: 'ENOENT', syscall: 'spawn sh' }
sh exit code 1
Unhandled rejection Error: spawn sh ENOENT
    at notFoundError (C:\Users\arugnone\AppData\Roaming\nvm\v6.10.2\node_modules\all-nvm\node_modules\cross-spawn-async\lib\enoent.js:8:11)
    at verifyENOENT (C:\Users\arugnone\AppData\Roaming\nvm\v6.10.2\node_modules\all-nvm\node_modules\cross-spawn-async\lib\enoent.js:43:16)
    at ChildProcess.cp.emit (C:\Users\arugnone\AppData\Roaming\nvm\v6.10.2\node_modules\all-nvm\node_modules\cross-spawn-async\lib\enoent.js:30:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

**Comment by bahmutov** [comment]
Hmm, I don't have access to Windows machine, maybe using something like cross-env would help?
